### PR TITLE
Multithreaded Display and Can Communication

### PR DESCRIPTION
**Pull request by cosparks**
Just building on Apoorvs work. This PR contains his changes with the addition of:

• a new background thread for updating the display
• new large font for displaying speed and time values
• code defining symbols for different values
• reformatted throttle values scaling potentiometer range [0.28, 0.425] to [0, 255]
• debug macro for easily switching between nucleo's serial and TFT display (because they can only be used in exclusion of each other)
• can message parsing and updating for speed and bms voltage
• some general tidying and documentation to make the code a bit more user-friendly

I really just threw it all into main but it's growing quickly enough that it will probably have to be refactored at some point

### CODE REVIEW

**Comment by apoorvgargubc1998** [comment]
@cosparks  I think the `   if (hazardVal) {
        leftbVal = 0;
        rightbVal = 0;
    }` on line 123 -127 in main.cpp is not correct. The logic is supposed to be that left and right blinkers bits should be 1 if the hazards bit is 1.  @Yoruio should be able to further explain this

**Review by silviu-toderita — APPROVED** [review]
Looks great, thanks for getting this done so quickly

**Comment by cosparks** [comment]
>  I think the if (hazardVal) { leftbVal = 0; rightbVal = 0; } on line 123 -127 in main.cpp is not correct

@Yoruio I'm a bit confused as to why there is a hazards bit in the can operation message if it doesn't mean anything.  Is that to be ignored entirely?

**Comment by silviu-toderita** [comment]
Check with @Yoruio (Roy), but I believe he's no longer using the hazard bit at all. So in this case, hazards would just have to turn on both left and right blinkers. 

A couple of special things to keep in mind here:
- When one blinker is on and hazards are then turned on, that blinker should be turned off and then both blinkers turned on again so that they are in sync
- When hazards are turned off but one of the blinkers should remain on, remember to not turn it off

**Pull request merged**
